// <auto-generated />
using System;
using LedBlinker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LedBlinker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728054431_ZmenaLed")]
    partial class ZmenaLed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("LedBlinker.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BlinkRate")
                        .HasColumnType("REAL");

                    b.Property<int>("ConfigurationLedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationLedId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("LedBlinker.Models.Led", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Leds");
                });

            modelBuilder.Entity("LedBlinker.Models.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("LedBlinker.Models.Configuration", b =>
                {
                    b.HasOne("LedBlinker.Models.Led", "ConfigurationLed")
                        .WithMany()
                        .HasForeignKey("ConfigurationLedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationLed");
                });
#pragma warning restore 612, 618
        }
    }
}
